### ISSUE TITLE
Issue with painterfitsexport and fits_write_key

### ISSUE THREAD

**Issue by kluskaj** [andferrari/PAINTER.jl#9]
Trying to export results of an image reconstruction to a fits file using painterfitsexport after running "paintertest.jl"
Having the error: fits_write_key not defined.

fits_write_key is defined by using FITSIO.Libcfitsio
I have added that to Painter.jl.
The rerun "paintertest.jl" and painterfitsexport
A new error appeared:
WARNING: ccall Ptr argument types must now match exactly, or be Ptr{Void}.
WARNING: ccall Ptr argument types must now match exactly, or be Ptr{Void}.
WARNING: ccall Ptr argument types must now match exactly, or be Ptr{Void}.
WARNING: ccall Ptr argument types must now match exactly, or be Ptr{Void}.
WARNING: ccall Ptr argument types must now match exactly, or be Ptr{Void}.
WARNING: ccall Ptr argument types must now match exactly, or be Ptr{Void}.
WARNING: ccall Ptr argument types must now match exactly, or be Ptr{Void}.
WARNING: ccall Ptr argument types must now match exactly, or be Ptr{Void}.
WARNING: ccall Ptr argument types must now match exactly, or be Ptr{Void}.
WARNING: (fits_write_col{T})(f::FITSFile,::Type{T},colnum::Integer,firstrow::Integer,firstelem::Integer,data::Array{T}) is deprecated, use fits_write_col(f,colnum,firstrow,firstelem,data) instead.
WARNING: (fits_write_col{T})(f::FITSFile,::Type{T},colnum::Integer,firstrow::Integer,firstelem::Integer,data::Array{T}) is deprecated, use fits_write_col(f,colnum,firstrow,firstelem,data) instead.
WARNING: (fits_write_col{T})(f::FITSFile,::Type{T},colnum::Integer,firstrow::Integer,firstelem::Integer,data::Array{T}) is deprecated, use fits_write_col(f,colnum,firstrow,firstelem,data) instead.
WARNING: (fits_write_col{T})(f::FITSFile,::Type{T},colnum::Integer,firstrow::Integer,firstelem::Integer,data::Array{T}) is deprecated, use fits_write_col(f,colnum,firstrow,firstelem,data) instead.
WARNING: (fits_write_col{T})(f::FITSFile,::Type{T},colnum::Integer,firstrow::Integer,firstelem::Integer,data::Array{T}) is deprecated, use fits_write_col(f,colnum,firstrow,firstelem,data) instead.
WARNING: (fits_write_col{T})(f::FITSFile,::Type{T},colnum::Integer,firstrow::Integer,firstelem::Integer,data::Array{T}) is deprecated, use fits_write_col(f,colnum,firstrow,firstelem,data) instead.
ERROR: column number < 1 or > tfields

Nevertheless, a fits file is created with the image only a no ohter information in the header (no information on the axis scale, etc...)

Other information:
tried on julia v0.3.11 and v0.3.8
Other errors on julia v0.4 prevented me to test it on this version as well...

Thank you for your help!

**Comment by kluskaj** [comment]
on painter v0.3.11 I got this error after including the "using FITSIO.Libcfitsio" in painter.jl:
error compiling **painterfitsexport#360**: unsupported or misplaced expression using function **painterfitsexport#360**

**Comment by andferrari** [comment]
solved in [PAINTER.jl/pull/12](https://github.com/andferrari/PAINTER.jl/pull/12)
